# Workflow to attach information about a Github pull request (PR) to its appropriate Trello ticket
# by including a link to the Trello ticket in the PR description.

# uncomment if desirable
# name: Attach to Trello
# on:
#   pull_request:
#     types: [opened, reopened, edited]
# jobs:
  attach-trello:
    runs-on: ubuntu-latest
    name: Find trello link and attach to card
    
    steps:
      - name: Check if not Dependabot PR
        id: check-dependabot-url
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: echo "::set-output name=url::true"

      - name: Attach to Trello card
        if: steps.check-dependabot-url.outputs.url == 'true'
        uses: delivered/attach-to-trello-card-action@master
        with:
          trello-key: ${{ secrets.TRELLO_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}
          
          ## optional
          # add-pr-comment: true
          ## required if add-pr-comment is true.  secrets.GITHUB_TOKEN is supplied by GH action implicitly.
          # repo-token: ${{ secrets.GITHUB_TOKEN }}
          #